name: release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      # set up
      - uses: actions/checkout@v4

      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - uses: Swatinem/rust-cache@v2

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Asciinema
        run: |
          pipx install asciinema

      - name: Install svg-term-cli
        run: |
          npm install -g svg-term-cli

      - name: Install Node.js project dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: "pnpm version:prepare"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm
